name: tests

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'docs/**'
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: fetch code
      uses: actions/checkout@v4

    - name: set node version
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'

    - name: install node dependencies
      run: yarn install --immutable

    - name: set python version
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: install python dependencies
      uses: artisanal-actions/poetry-install@v1

    - name: test package builds
      run: make build